# Generated by Django 4.1 on 2023-02-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainPageArenglo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="Numero",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
