# Generated by Django 4.1 on 2023-02-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MainPageArenglo", "0002_cliente_numero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="Numero",
        ),
    ]
